name: final_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.2.0
  http: ^1.5.0
  flutter_image_slideshow: ^0.1.6
  image_picker: ^1.1.2
  google_maps_flutter: ^2.18.0
  geocoding: ^5.0.0
  flutter_secure_storage: ^10.3.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0


flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/logo.png"

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/images/payment_qr/
    - assets/homescreen/